### ISSUE TITLE
Comparing submitter phenotype data w/GenomeConnect in ClinVar

### ISSUE THREAD

**Issue by hdziadzio** [clingen-data-model/genomeconnect-report#10]
Request from Jules/GenomeConnect team:

> A question came up recently regarding GenomeConnect ClinVar submissions and our ability to compare to other submitters’ phenotype data. Do you know if there is easy way to determine if any of the variants submitted by GenomeConnect have other submitters that provided structured HPO terms as part of the submission? Essentially, we would like to understand how many variants we have shared (https://www.ncbi.nlm.nih.gov/clinvar/submitters/506185/) where another submitter has provided phenotype data.

**Comment by dazzariti** [comment]
@larrybabb Regarding prioritization for this, they would need this data by late September, leadership agrees it is worth doing, but does not need to be prioritized immediately

**Comment by dazzariti** [comment]
@larrybabb I'm updating this ticket from today's discussion - please make any changes in case I captured this incorrectly.

To clarify - we are looking to compare HPO terms submitted in the "Clinical Features" field - not submitted as a Condition

**Comment by larrybabb** [comment]
@dazzariti Here’s the first pass at the hpo findings comparisons between the GenomeConnect submissions and others for the same variants. The first 410 or so are comparisons and the remaining are just a record of what was submitted by GC since there were no other submissions on those variants

https://docs.google.com/spreadsheets/d/1DSE_NTpCg3qvlJJTHNz4jPfScvxUavrRy2SpDp3w_ks/edit
